[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/en"
  to = "/index-en.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/index-en.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production" 